#+BEGIN_COMMENT
.. title: 在linux的信号处理函数中不要进行锁相关操作
.. slug: linux-signal-handler-callback-mutex
.. date: 2019-10-26 21:41:50 UTC+08:00
.. tags: linux, signal handler, mutex, sigwait, sigtimedwait
.. category: linux
.. link:
.. description:
.. type: text
/.. status: draft
#+END_COMMENT
#+OPTIONS: num:t

#+TITLE: 在linux的信号处理函数中不要进行锁相关操作

最近在写一个linux程序，其中一个逻辑是要等待信号（signal），我使用了条件变量（condition variable）来完成这个操作，但是实际效果却是整个程序卡住了，经过查阅资料后得知在信号处理函数中是不能进行锁操作的。

{{{TEASER_END}}}

** 问题现象
最初的情况是，我在信号处理函数中打印了日志，在收到信号时有时会导致整个程序卡死。使用 ~pstack~ 观察程序的运行状态，发现程序卡在写日志的加锁操作中。由于程序是多线程的，所以为了保证在输出日志时线程间能够同步，在写日志时进行了加锁操作。在将写日志的语句注释掉后，程序就能够正常运行了。一开始我怀疑是日志模块出了问题，经过反复排查后，并没有发现明显的问题。随着开发的推进，当我在信号处理函数中进行条件变量操作的时候，程序再一次卡死了，我开始怀疑是线程同步的相关操作中出现了问题。

** 信号处理函数中不进行锁操作
信号处理函数将会在同一个线程中执行，如果在信号处理函数中进行加锁，则可能会引起互锁。
如果必须要完成对锁的操作呢，妥协办法是在信号处理函数中创建一个线程，在该线程中进行锁相关的操作。

实际上，在信号处理函数中的操作要求是“可重入的”（reentrancy），有很多系统调用也是受限制的。以下是 *可以* 在信号处理函数中调用的系统函数。

#+BEGIN_SRC org
access       alarm         cfgetispeed   cfgetospeed    cfsetispeed   cfsetospeed
chdir        chmod         chown         close          creat         dup
dup2         execle        execve        _exit          fcntl         fork
fstat        getgroups     getpgrp       getpid         getppid       getuid
kill         link          lseek         mkdir          mkfifo        open
pathconf     pause         pipe          read           rename        rmdir
setgid       setpgid       setsid        setuid         sigaction     sigaddset
sigdelset    sigemptyset   sigfillset    sigismember    sigpending    sigprocmask
sigsuspend   sleep         stat          sysconf        tcdrain       tcflow
tcflush      tcgetattr     tcgetpgrp     tcsendbreak    tcsetattr     tcsetgrp
time         times         umask         uname          unlink        utime
wait         waitpid       write
#+END_SRC

** 使用 ~sigwait~ 和 ~sigtimedwait~ 等待线程
为了实现等待某个信号的操作，可以采用 ~sigwait~ 和 ~sigtimedwait~ 来做。这两个函数会阻塞当前线程的执行以等待即将到来的信号。
思考： ~sigwait~ 如何应对有多个信号需要等待，每个信号的所对应的处理流程都不一样，而且信号接收的顺序可能有变化。

** 参考资料
- [[https://stackoverflow.com/questions/32413397/why-it-is-problematic-to-use-mutex-locks-within-signal-handers][stackoverflow - mutex locks within signal handler]]
- [[https://stackoverflow.com/questions/12445618/accessing-shared-data-from-a-signal-handler][stackoverflow - access shared data from signal handler]]
- [[http://maxim.int.ru/bookshelf/PthreadsProgram/htm/r_40.html][pthreads program - ch5 pthreads and unix]]
- [[https://www.ibm.com/support/pages/mutex-bad-signal-context][ibm support - mutex bad signal context]]
- [[https://linux.die.net/man/2/sigtimedwait][linux man - sigtimedwait]]
- [[https://linux.die.net/man/3/sigwait][linux man - sigwait]]
