#+BEGIN_COMMENT
.. title: Linux常用命令行指令 - lsof
.. slug: linux-command-examples-lsof
.. date: 2018-03-21 20:28:34 UTC+08:00
.. tags: linux, shell
.. category: linux
.. link: https://www.thegeekstuff.com/2012/08/lsof-command-examples/
.. description: 
.. type: text
#+END_COMMENT

#+TITLE:Linux常用命令行指令 - lsof

lsof是list open files的简称，用于列出系统中所有打开的文件。由于在linux系统下，所有 对象都是文件，所以这个指令十分有用。

下面就给出了几种常见的用法，需要注意的是有些指令需要root权限执行。

** 1. 查看打开指定文件的进程
#+BEGIN_SRC shell
lsof /var/syslog.log
#+END_SRC

** 2. 查看指定目录下打开的文件
#+BEGIN_SRC shell
lsof +D /home/
#+END_SRC

** 3. 查看以指定进程名所有打开的文件
使用 =-c= 命令能够查看指定进程名使用的文件，允许在一个命令行指令中使用多个 =-c= 参数。
#+BEGIN_SRC shell
lsof -c procname
#+END_SRC

** 4. 查看使用指定挂载点的进程
在停止挂载某个目录时，系统会告诉我们“设备资源繁忙”，所以我们需要找出使用挂载点的程序，终止这些进程，解除目录的占用状态。
#+BEGIN_SRC shell
lsof /home
#+END_SRC
或
#+BEGIN_SRC shell
lsof +D /home/
#+END_SRC

** 5. 查看指定用户打开的文件
#+BEGIN_SRC shell
lsof -u username
#+END_SRC
另外还可以进行反向过滤，在输出中不显示指定用户的文件，语法如下。
#+BEGIN_SRC shell
lsof -u ^username
#+END_SRC

** 6. 查看指定进程打开的文件
#+BEGIN_SRC shell
lsof -p pid
#+END_SRC

** 7. 终止属于某个用户的所有进程
#+BEGIN_SRC shell
kill `lsof -t -u username`
#+END_SRC
相似的，可以使用 =-t= 参数打印使用某个文件的进程id。
#+BEGIN_SRC shell
lsof -t /var/log
#+END_SRC

** 8. 让结果同时满足多个选项
默认情况下，多个参数是以或（or）进行操作的，可以使用 =-a= 选项让结果同时满足多个参数。
#+BEGIN_SRC shell
lsof -a -u username -c procname
#+END_SRC

** 9. 让命令重复执行
可以使用 =-r= 参数让命令重复执行。以下命令会每隔5s执行一次，每次的执行结果会用 “====” 分割开。
#+BEGIN_SRC shell
lsof -u username -c procname -a -r5
#+END_SRC

** 10. 列出所有的网络连接
#+BEGIN_SRC shell
lsof -i
#+END_SRC
让结果中的ip地址和端口号显示数字而不是英文别名
#+BEGIN_SRC shell
lsof -i -Pn
#+END_SRC
显示所有的 =AF_UNIX= socket
#+BEGIN_SRC shell
lsof -U
#+END_SRC

** 11. 列出指定进程使用的网络连接
#+BEGIN_SRC shell
lsof -i -a -p pid
#+END_SRC

** 12. 查看指定端口上的监听
#+BEGIN_SRC shell
lsof -i :portid
#+END_SRC

** 13. 列出所有tcp和udp连接
#+BEGIN_SRC shell
lsof -i tcp; lsof -i udp
#+END_SRC

** 14. 列出所有的网络文件系统
网络文件系统（network file system）
#+BEGIN_SRC shell
lsof -N -u username
#+END_SRC


