
# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty
#relative_permalinks: true


# Site settings
title:          Noob-Coder
tagline:        ''
description:    "Samson's tech-blog"  
url:            http://samsonwang.me
baseurl:        ''
paginate:       5

# About/contact
owner:
  name: "Samson"
  email: zl.wang@foxmail.com
  bio: "Noob coder"


