#+BEGIN_COMMENT
.. title: 每周算法：两个整数相除
.. slug: algorithm-weekly-divide-two-integers
.. date: 2018-10-11 17:59:07 UTC+08:00
.. tags: algorithm, leetcode
.. category: algorithm
.. link: https://leetcode.com/problems/divide-two-integers/description/
.. description:
.. type: text
.. status: draft
#+END_COMMENT

#+TITLE: 每周算法：两个整数相除

leetcode算法题第29道，难度为medium。

{{{TEASER_END}}}

** Description
Given two integers dividend and divisor, divide two integers without using multiplication, division and mod operator.
Return the quotient after dividing dividend by divisor.
The integer division should truncate toward zero.

*Example 1:*
#+BEGIN_EXAMPLE
Input: dividend = 10, divisor = 3
Output: 3
#+END_EXAMPLE

*Example 2:*
#+BEGIN_EXAMPLE
Input: dividend = 7, divisor = -3
Output: -2
#+END_EXAMPLE

*Note:*
- Both dividend and divisor will be 32-bit signed integers.
- The divisor will never be 0.
- Assume we are dealing with an environment which could only store integers within the 32-bit signed integer range: [−2^31,  2^31 − 1]. For the purpose of this problem, assume that your function returns 2^31 − 1 when the division result overflows.

来源：[[https://leetcode.com/problems/divide-two-integers/description/][leetcode 29 divide to integers]]

** Solution
*** Approach 1
