#+BEGIN_COMMENT
.. title: 网关简介
.. slug: brief-intro-to-gateway
.. date: 2018-10-20 16:20:39 UTC+08:00
.. tags: network, gateway, router
.. category: network
.. link:
.. description:
.. type: text
#+END_COMMENT

#+TITLE: 网关简介

网关是在网络通信中常常被提起的一个词，它究竟是什么，它其中包含哪些知识点呢？本文将带你了解网关的一些基础概念。

{{{TEASER_END}}}

** 网络网关（广义上的网关）
网关是一种网络通信中使用的硬件设备，它能在不同的独立网络(discrete network)之间传递数据。网关可以同时使用多种通信协议，它可以工作在OSI模型7层中的任何层。

网络网关提供系统间互通功能，它可能包含协议解析、阻抗匹配、频率转换、错误隔离、信号转换等模块。它要求在两个网络之间建立相互可接受的监管流程。网关还可以进行协议转换和协议映射，通过执行所需的协议转换，连接使用不同通信协议的网络。

** IP网关（狭义上的网关）
IP协议是目前使用最广泛的网络通信协议，所以我们经常听到的网关基本上都是IP网关。

在IP网络中，客户端在向所在子网外发送IP数据包时，会自动发送到网络网关。在转发一个IP数据包时，可能会根据需要进行网络地址转换。

默认网关是使用IP协议中的一个网络节点，它负责将目的IP地址没有匹配任何路由规则的数据包转发出去。

大多数路由器都有网关功能，其他设备（如PC机或服务器）也可以有网关功能。

** 网关和路由
*相同点：* 网关和路由都是用来调整不同网络之间的数据流量的。可以通过安装两块网卡，并将每块网卡绑定在两个不同的网路上，这样该设备就能完成两个网络之间的流量调整了。

*不同点：* 网关可以调整两种网络（dissimilar）之间的流量，路由只能调整相似网络（similar）之间的流量。

路由可以用于分割网络上的流量，以此减少流经网络的流量，此功能在真正的大型网络中非常有用。可以使用路由器将网络划分为多个子网，从而仅允许专门针对不子网的流量流过路由器。
假设有一个使用TCP/IP协议的网络，由于TCP/IP也是互联网的主要协议，因此您以使用路由器将本地网络连接到互联网。路由器会保证：
- 用于本地网络通信的流量不会流入互联网中
- 目的地不是本地网络的互联网流量留在互联网上

网关可以连接不同的网络系统。例如，将PC机网络与3270大型机环境连接的设备，需要支持Windows NT网络与NetWare网络通信。尽管网关也可用于减少网络流量，但它更常用于在不同的系统中进行通信。

** 参考资料
- [[https://en.wikipedia.org/wiki/Gateway_(telecommunications)][wikipedia - gateway]]
- [[https://www.techrepublic.com/article/understanding-the-differences-between-gateways-and-routers/][techrepulic.com - understanding the difference between gatewats and routers]]

（完）
