#+BEGIN_COMMENT
.. title: 网关简介
.. slug: brief-intro-to-gateway
.. date: 2018-10-18 20:17:39 UTC+08:00
.. tags: network, gateway, router
.. category: network
.. link:
.. description:
.. type: text
.. status: draft
#+END_COMMENT

#+TITLE: 网关简介

网关是在网络通信中常常被提起的一个词，它究竟是什么，它其中包含哪些知识点呢？本文将带你了解网关的一些基础概念。

{{{TEASER_END}}}

** 网络网关（广义上的网关）
网关是一种网络通信中使用的硬件设备，它能在不同的独立网络之间传递数据。网关可以同时使用多种通信协议，它可以工作在OSI模型7层中的任何层。

网络网关提供系统间互通功能，它可能包含协议解析、阻抗匹配、频率转换、错误隔离、信号转换等模块。


** IP网关
On an Internet Protocol (IP) network, clients automatically send IP packets with a destination outside a given subnet mask as defined by a combination of network address and subnet mask to a network gateway. For example, if a private network has a base IP address of 192.168.0.0 and has a subnet mask of 255.255.255.0, then any data going to an IP address outside of 192.168.0.X will be sent to that network's gateway. While forwarding an IP packet to another network, the gateway might or might not perform Network Address Translation.

A gateway is an essential feature of most routers, although other devices (such as any PC or server) can function as a gateway.

Most computer operating systems make use of the terms described above. Microsoft Windows, however, describes this standard networking feature as Internet Connection Sharing, which acts as a gateway, offering a connection between the Internet and an internal network.

Network addresses in the form "0.0.0.0" represent only the IPv4 version of the IP protocol. The format is different in an IPv6 address.[1]

** 网关和路由


** 参考资料
- [[https://en.wikipedia.org/wiki/Gateway_(telecommunications)][wikipedia - gateway]]


（完）
