#+BEGIN_COMMENT
.. title: Linux下的fifo、pipe、unix domain socket漫谈
.. slug: fifo-pipe-unix-domain-socket
.. date: 2018-04-09 13:03:25 UTC+08:00
.. tags: draft, linux
.. category: linux
.. link: 
.. description: 
.. type: text
#+END_COMMENT


#+TITLE: Linux下的FIFO、pipe、unix domain socket漫谈

在做Linux开发时，经常会接触 =管道= 、 =AF_UNIX= 等相关词汇，为了弄清他们之间的关系，查阅了一些资料，将结果整理并记录下来。

** =FIFO= 与 =pipe= 的比较
FIFO可以通过 =mkfifo fifo_file= 在本地创建一个文件用来表示一个管道，数据的交换是在操作系统内核完成的，所以在文件中没有内容。
FIFO可以看做是一个带有名字的管道。
#+BEGIN_QUOTE
A FIFO special file (a named pipe) is similar to a pipe, except that it is accessed as part of the file system. It can be opened by multiple processes for reading or writing. When processes are exchanging data via the FIFO, the kernel passes all data internally without writing it to the file system. Thus, the FIFO special file has no contents on the file system; the file system entry merely serves as a reference point so that processes can access the pipe using a name in the file system.
#+END_QUOTE
以上内容截取自Linux的帮助文档（ =man fifo= ）


** =fifo= 与 =unix domain socket= 的比较

** =unix-domain-socket= 与 =tcp socket= 的比较






https://unix.stackexchange.com/questions/75904/are-fifo-pipe-unix-domain-socket-the-same-thing-in-linux-kernel
https://serverfault.com/questions/124517/whats-the-difference-between-unix-socket-and-tcp-ip-socket?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
https://unix.stackexchange.com/questions/236983/differences-between-unix-domain-sockets-and-network-sockets?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
https://stackoverflow.com/questions/14973942/performance-tcp-loopback-connection-vs-unix-domain-socket
https://lists.freebsd.org/pipermail/freebsd-performance/2005-February/001143.html

