#+BEGIN_COMMENT
.. title: 路由、调制解调器和交换机
.. slug: router-modem-and-switch
.. date: 2018-09-27 18:34:54 UTC+08:00
.. tags: network, router, moderm, switch
.. category: network
.. link:
.. description:
.. type: text
#+END_COMMENT

#+TITLE: 路由、调制解调器和交换机

路由、调制解调器和交换机，这三个是我们经常使用的网络设备。它们在网络中的作用是什么？它们工作在网络模型的哪一层？本篇文章将带你了解他们的原理与和区别。

{{{TEASER_END}}}

** 路由
路由器（router）的作用是连接多个逻辑上分开的网络，逻辑网络是代表一个单独的网络或者一个子网。当数据从一个子网传输到另一个子网时，可通过路由器的路由功能来完成。路由器工作在OSI参考模型第三层网络层。路由器通过动态维护路由表来反映当前的网络拓扑，并通过网络上其他路由器交换路由和链路信息来维护路由表。

路由器具有判断网络地址和选择IP路径的功能，它能在多网络互连环境中，建立灵活的连接。路由器根据收到数据包中的网络层地址以及路由器内部维护的路由表决定输出端口以及下一跳地址，并且重写链路层数据包头实现转发数据包。

以家用路由器为例，路由连接了因特网和本地网络。路由器使多个设备用同一个物理网络连接接入因特网。连接到同一个路由器的设备可以借助本地网络进行通信。对于互联网而言，所有家中的设备产生的网络流量好像是来源于一个设备，也就是路由器。另外，路由器还会对连接它的设备起到一定的保护作用，这些设备就不会直接暴露在互连网中。

** 调制解调器
调制解调器（modem）的作用是将计算机的数字信号转换为可沿对电话线传送的模拟信号，而这些模拟信号又可被线路另一端的另一个调制解调器接收，并译成计算机可懂的语言。modem这个名字是modulator（调制器）与demodulator（解调器）的简称。这是一个比较老的概念了，以前的网络提供商通过电话线传输数据，现在大多数直接光线入户，也就省去了调制解调器了。

** 交换机
交换机工作在OSI参考模型的链路层。交换机内部会在每个端口成功连接时，通过将MAC地址和端口对应，形成一张MAC表。在今后的通讯中，发往该MAC地址的数据包将仅送往其对应的端口，而不是所有的端口。因此，交换机可用于划分数据链路层广播，即冲突域；但它不能划分网络层广播，即广播域。

交换机拥有一条很高带宽的背部总线和内部交换矩阵。交换机的所有的端口都挂接在这条背部总线上，控制电路收到数据包以后，处理端口会查找内存中的地址对照表以确定目的MAC（网卡的硬件地址）的NIC（网卡）挂接在哪个端口上，通过内部交换矩阵迅速将数据包传送到目的端口，目的MAC若不存在，广播到所有的端口，接收端口回应后交换机会“学习”新的MAC地址，并把它添加入内部MAC地址表中，通过在数据帧的始发者和目标接收者之间建立临时的交换路径，使数据帧直接由源地址到达目的地址。。

交换机在同一时刻可进行多个端口对之间的数据传输。每一端口都可视为独立的物理网段（注：非IP网段），连接在其上的网络设备独自享有全部的带宽，无须同其他设备竞争使用。当节点A向节点D发送数据时，节点B可同时向节点C发送数据，而且这两个传输都享有网络的全部带宽，都有着自己的虚拟连接。假使这里使用的是10Mbps的以太网交换机，那么该交换机这时的总流通量就等于2×10Mbps=20Mbps，而使用10Mbps的共享式HUB时，一个HUB的总流通量也不会超出10Mbps。总之，交换机是一种基于MAC地址识别，能完成封装转发数据帧功能的网络设备。

** 参考资料
- [[https://www.howtogeek.com/234233/whats-the-difference-between-a-modem-and-a-router/][howtogeek.com - difference between modem and router]]
- [[https://baike.baidu.com/item/%E8%B7%AF%E7%94%B1%E5%99%A8][百度百科 - 路由器]]
- [[https://baike.baidu.com/item/%E8%B0%83%E5%88%B6%E8%A7%A3%E8%B0%83%E5%99%A8][百度百科 - 调制解调器]]
- [[https://baike.baidu.com/item/%E4%BA%A4%E6%8D%A2%E6%9C%BA/][百度百科 - 交换机]]
