#+BEGIN_COMMENT
.. title: TCP协议（RFC793）
.. slug: transmission-control-protocol
.. date: 2018-09-28 21:56:05 UTC+08:00
.. tags: network, tcp, ip
.. category: network
.. link:
.. description:
.. type: text
.. status: draft
#+END_COMMENT

#+TITLE: TCP协议（RFC793）

传输控制协议（TCP协议）是因特网协议栈中很重要的一个协议，它是IP协议的补充。TCP协议提供基于IP网络的可靠的、有序的、查错的（error checked）节流传输。主流网络应大多基于TCP协议的。TCP协议格式由RFC793定义，本文是RFC793的要点摘录。

{{{TEASER_END}}}

** 概述
TCP is a connection-oriented, end-to-end reliable protocol designed to fit into a layered hierarchy of protocols which support multi-network applications. The TCP provides for reliable inter-process communication between pairs of processes in host computers attached to distinct but interconnected computer communication networks.

The TCP is intended to provide a reliable process-to-process communication service in a multinetwork environment. The TCP is intended to be a host-to-host protocol in common use in multiple networks.

TCP包含下列功能:
- Basic Data Transfer
- Reliability
- Flow Control
- Multiplexing
- Connections
- Precedence and Security





TCP协议是传输层通讯协议。
Applications that do not require reliable data stream service may use the User Datagram Protocol (UDP), which provides a connectionless datagram service that emphasizes reduced latency over reliability.


** 参考资料
- https://tools.ietf.org/html/rfc793
- https://en.wikipedia.org/wiki/Transmission_Control_Protocol
