#+BEGIN_COMMENT
.. title: 为什么要使用各种前端框架
.. slug: why-front-end-libraries
.. date: 2018-08-27 22:10:35 UTC+08:00
.. tags: draft, front-end, javascript, css, html
.. category: front-end
.. link:
.. description:
.. type: text
#+END_COMMENT

#+TITLE: 为什么要使用各种前端框架

** 引言
在学习前端的过程中，我开始接触到许多开发框架或开发工具，这些工具让我开始眼花缭乱。使用常规的html/css/js就已经能够开发出这种网页了，所以我问自己，为什么要学习这些框架或工具，这些库是用来解决什么问题的。想明白这个问题，我学习的目的就更加明确，在遇到一些开发情景时，也能够快速准确地挑选出应该使用的框架。

下面按照我目前的理解，对目前的主流的前端开发库进行一些分析和比较。由于我还是一个初学着，所以我的观点可能还不是很成熟。

** 为什么要使用jQuery
jQuery是一个轻量级js库，它有如下特性：
- 简化了HTML/DOM操作
- CSS选择器
- 动画特效支持
- 解决跨浏览器的兼容行问题
- 完善的Ajax支持

在查阅资料的过程中，我还听到一些主张停用jQuery的声音。原因就在于随着前端开发生态不断的完善，现代浏览器原生API已经足够好用。

** 为什么要使用SASS
SASS是一种CSS预编译格式，它最终会编译成CSS。
SASS提供了CSS语法的拓展，它支持变量，算数运算符，循环操作，函数操作，样式模板（mixin）等强大的特性。它能够让开发人员更方便地编写CSS。SASS支持 =import= 关键字，这样就能够很方便地对样式进行模块化设计。

加一句题外话，在使用SASS时，需要考虑的另一个问题就是代码物理结构的安排（直白的说就是目录的划分，源文件的存放位置等），这也是所有代码开发中需要注意的问题。

与SASS相似的工具还有LESS。

** 为什么要使用Bootstrap




** 为什么要使用React




** 为什么要使用Rudex



** 参考资料
- [[https://www.w3schools.com/jquery/jquery_intro.asp][w3schools jQuery intro]]
- [[https://github.com/nefe/You-Dont-Need-jQuery][github you don't need jQuery]]
- [[https://www.mugo.ca/Blog/7-benefits-of-using-SASS-over-conventional-CSS][7 benefits of SASS]]
